version: "3.9"

services:
  backend:
    build: ./backend
    container_name: pib-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    # No sobrescribir el c√≥digo del contenedor
    # No sobrescribir el comando del Dockerfile

  frontend:
    build: ./frontend
    container_name: pib-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - BACKEND_URL=http://pib-backend:8000
    command: npm run dev

  db:
    image: postgres:16
    container_name: pib-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pilotdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: